#!/bin/sh  
#  
#chkconfig: 2345 80 90  
#description: mongodb  
start() {  
  [ -e "/tmp/mongodb-27017.sock" ] && echo "mongodb 已启动" && exit
  /data/mongodb/bin/mongod -f /data/mongodb/etc/mongodb.conf 
}  
  
stop() {  
  [ -e "/tmp/mongodb-27017.sock" ] &&  
  /data/mongodb/bin/mongod -f /data/mongodb/etc/mongodb.conf --shutdown  
}  
  
case "$1" in  
  start)  
 start  
 ;;  
  stop)  
 stop  
 ;;  
  restart)  
 stop  
 start  
 ;;  
  *)  
 echo $"Usage: $0 {start|stop|restart}"  
 exit 1  
esac
